/**
 * Button Component ARIA Conformance Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that rootProps() returns correct ARIA attributes per state.
 */

import { test, expect, describe } from 'bun:test';
import { useButton } from '../button/solid/useButton';

/**
 * ARIA Conformance Tests
 */
describe('Button ARIA Conformance', () => {
    test('rootProps() returns object with ARIA attributes', () => {
        const hook = useButton({});
        const props = hook.rootProps();
        expect(typeof props).toBe('object');
    });

    test('rootProps() includes aria-busy', () => {
        const hook = useButton({});
        const props = hook.rootProps();
        expect('aria-busy' in props).toBe(true);
    });

    test('rootProps() includes aria-disabled', () => {
        const hook = useButton({});
        const props = hook.rootProps();
        expect('aria-disabled' in props).toBe(true);
    });

});
