/**
 * Checkbox Hook Test: useCheckbox conformance and prop cycling
 * AUTO-GENERATED by rubigo-build – do not edit
 */

import { test, expect, describe } from 'bun:test';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { createSignal, createRoot } from 'solid-js';
import { useCheckbox } from '../checkbox/solid/useCheckbox';

interface UnifiedVectors {
    component: string;
    scenarios: Array<{
        name: string;
        source: 'yaml' | 'itf';
        steps: Array<{
            event: string;
            before: { context: Record<string, unknown>; state: string };
            after: { context: Record<string, unknown>; state: string };
        }>;
    }>;
}

function loadVectors(): UnifiedVectors | null {
    const vectorsPath = join(process.cwd(), '..', 'generated', 'test-vectors', 'checkbox.unified.json');
    if (!existsSync(vectorsPath)) {
        console.warn(`No unified vectors found at ${vectorsPath}`);
        return null;
    }
    return JSON.parse(readFileSync(vectorsPath, 'utf-8'));
}

describe('Checkbox Hook Conformance', () => {
    const vectors = loadVectors();

    if (!vectors) {
        test.skip('No vectors available - run just unify-vectors first', () => { });
        return;
    }

    test('loads unified vectors', () => {
        expect(vectors.component).toBe('checkbox');
        expect(vectors.scenarios.length).toBeGreaterThan(0);
    });
});

/**
 * Prop Cycling Tests
 * 
 * These tests verify that boolean props can be cycled multiple times
 * on the SAME hook instance without state corruption.
 */
describe('Checkbox Prop Cycling', () => {
    test('checked cycling: false→true→false→true (same instance)', () => {
        createRoot((dispose) => {
            const [props, setProps] = createSignal({ checked: false });
            const hook = useCheckbox(() => props());
            
            expect(hook.checked()).toBe(false);
            setProps({ checked: true });
            expect(hook.checked()).toBe(true);
            setProps({ checked: false });
            expect(hook.checked()).toBe(false);
            setProps({ checked: true });
            expect(hook.checked()).toBe(true);
            
            dispose();
        });
    });

    test('disabled cycling: false→true→false→true (same instance)', () => {
        createRoot((dispose) => {
            const [props, setProps] = createSignal({ disabled: false });
            const hook = useCheckbox(() => props());
            
            expect(hook.disabled()).toBe(false);
            setProps({ disabled: true });
            expect(hook.disabled()).toBe(true);
            setProps({ disabled: false });
            expect(hook.disabled()).toBe(false);
            setProps({ disabled: true });
            expect(hook.disabled()).toBe(true);
            
            dispose();
        });
    });

    test('indeterminate cycling: false→true→false→true (same instance)', () => {
        createRoot((dispose) => {
            const [props, setProps] = createSignal({ indeterminate: false });
            const hook = useCheckbox(() => props());
            
            expect(hook.indeterminate()).toBe(false);
            setProps({ indeterminate: true });
            expect(hook.indeterminate()).toBe(true);
            setProps({ indeterminate: false });
            expect(hook.indeterminate()).toBe(false);
            setProps({ indeterminate: true });
            expect(hook.indeterminate()).toBe(true);
            
            dispose();
        });
    });

});

/**
 * Event Dispatch Tests
 */
describe('Checkbox Event Dispatch', () => {
    test('toggle() method exists and is callable', () => {
        const hook = useCheckbox({});
        expect(typeof hook.toggle).toBe('function');
    });

    test('setChecked() method exists and is callable', () => {
        const hook = useCheckbox({});
        expect(typeof hook.setChecked).toBe('function');
    });

    test('setUnchecked() method exists and is callable', () => {
        const hook = useCheckbox({});
        expect(typeof hook.setUnchecked).toBe('function');
    });

    test('setIndeterminate() method exists and is callable', () => {
        const hook = useCheckbox({});
        expect(typeof hook.setIndeterminate).toBe('function');
    });

});

/**
 * Accessor Reactivity Tests
 */
describe('Checkbox Accessor Reactivity', () => {
    test('checked() accessor returns boolean', () => {
        const hook = useCheckbox({});
        expect(typeof hook.checked()).toBe('boolean');
    });

    test('disabled() accessor returns boolean', () => {
        const hook = useCheckbox({});
        expect(typeof hook.disabled()).toBe('boolean');
    });

    test('indeterminate() accessor returns boolean', () => {
        const hook = useCheckbox({});
        expect(typeof hook.indeterminate()).toBe('boolean');
    });

});
