/**
 * Collapsible Keyboard Interaction Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that keyboard handlers are present and work correctly.
 */

import { test, expect, describe } from 'bun:test';
import { useCollapsible } from '../collapsible/solid/useCollapsible';

/**
 * Keyboard Handler Tests
 * 
 * Verify rootProps() includes keyboard event handlers.
 */
describe('Collapsible Keyboard Interactions', () => {
    test('rootProps() includes onKeyDown handler', () => {
        const hook = useCollapsible({});
        const props = hook.rootProps();
        expect(typeof props.onKeyDown).toBe('function');
    });

});
