/**
 * Dialog Component ARIA Conformance Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that rootProps() returns correct ARIA attributes per state.
 */

import { test, expect, describe } from 'bun:test';
import { useDialog } from '../dialog/solid/useDialog';

/**
 * ARIA Conformance Tests
 */
describe('Dialog ARIA Conformance', () => {
    test('rootProps() returns object with ARIA attributes', () => {
        const hook = useDialog({});
        const props = hook.rootProps();
        expect(typeof props).toBe('object');
    });

    test('rootProps() includes aria-hidden', () => {
        const hook = useDialog({});
        const props = hook.rootProps();
        expect('aria-hidden' in props).toBe(true);
    });

    test('rootProps() includes aria-modal', () => {
        const hook = useDialog({});
        const props = hook.rootProps();
        expect('aria-modal' in props).toBe(true);
    });

});
