/**
 * Select Component ARIA Conformance Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that rootProps() returns correct ARIA attributes per state.
 */

import { test, expect, describe } from 'bun:test';
import { useSelect } from '../select/solid/useSelect';

/**
 * ARIA Conformance Tests
 */
describe('Select ARIA Conformance', () => {
    test('rootProps() returns object with ARIA attributes', () => {
        const hook = useSelect({});
        const props = hook.rootProps();
        expect(typeof props).toBe('object');
    });

    test('rootProps() includes aria-disabled', () => {
        const hook = useSelect({});
        const props = hook.rootProps();
        expect('aria-disabled' in props).toBe(true);
    });

    test('rootProps() includes aria-expanded', () => {
        const hook = useSelect({});
        const props = hook.rootProps();
        expect('aria-expanded' in props).toBe(true);
    });

});
