/**
 * Slider Component ARIA Conformance Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that rootProps() returns correct ARIA attributes per state.
 */

import { test, expect, describe } from 'bun:test';
import { useSlider } from '../slider/solid/useSlider';

/**
 * ARIA Conformance Tests
 */
describe('Slider ARIA Conformance', () => {
    test('rootProps() returns object with ARIA attributes', () => {
        const hook = useSlider({});
        const props = hook.rootProps();
        expect(typeof props).toBe('object');
    });

    test('rootProps() includes aria-disabled', () => {
        const hook = useSlider({});
        const props = hook.rootProps();
        expect('aria-disabled' in props).toBe(true);
    });

    test('rootProps() includes aria-valuemax', () => {
        const hook = useSlider({});
        const props = hook.rootProps();
        expect('aria-valuemax' in props).toBe(true);
    });

    test('rootProps() includes aria-valuemin', () => {
        const hook = useSlider({});
        const props = hook.rootProps();
        expect('aria-valuemin' in props).toBe(true);
    });

    test('rootProps() includes aria-valuenow', () => {
        const hook = useSlider({});
        const props = hook.rootProps();
        expect('aria-valuenow' in props).toBe(true);
    });

});
