/**
 * Tabs Keyboard Interaction Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that keyboard handlers are present and work correctly.
 */

import { test, expect, describe } from 'bun:test';
import { useTabs } from '../tabs/solid/useTabs';

/**
 * Keyboard Handler Tests
 * 
 * Verify rootProps() includes keyboard event handlers.
 */
describe('Tabs Keyboard Interactions', () => {
    test('rootProps() includes onKeyDown handler', () => {
        const hook = useTabs({});
        const props = hook.rootProps();
        expect(typeof props.onKeyDown).toBe('function');
    });

    test('End key is documented: Focus last tab', () => {
        // This test documents expected behavior for End
        // Actual keyboard handling is tested via component integration tests
        const hook = useTabs({});
        expect(hook.rootProps).toBeDefined();
    });

    test('Home key is documented: Focus first tab', () => {
        // This test documents expected behavior for Home
        // Actual keyboard handling is tested via component integration tests
        const hook = useTabs({});
        expect(hook.rootProps).toBeDefined();
    });

    test('Tab key is documented: Enter/exit tablist, focus active tab', () => {
        // This test documents expected behavior for Tab
        // Actual keyboard handling is tested via component integration tests
        const hook = useTabs({});
        expect(hook.rootProps).toBeDefined();
    });

});
