/**
 * Staging Report Schema
 * 
 * Defines the structure of staging reports generated by stage-react.yml.
 * Version changes should be documented and schema updated accordingly.
 */

import { z } from "zod";

// Step outcome enum (matches GitHub Actions step outcomes)
const StepOutcome = z.enum(["success", "failure", "cancelled", "skipped"]);

// Individual step status
const StepStatus = z.object({
    status: StepOutcome,
});

// Steps tracked in the staging workflow
const StagingSteps = z.object({
    sanity_check: StepStatus,
    clone_database: StepStatus,
    install_deps: StepStatus,
    db_migration: StepStatus,
    build: StepStatus,
    initialization: StepStatus,
    health_check: StepStatus,
    e2e_tests: StepStatus,
});

/**
 * Staging Report Schema v1.0
 * 
 * Generated by: .github/workflows/stage-react.yml
 * Consumed by: /wip-stage workflow monitoring
 */
export const StagingReportV1 = z.object({
    // Schema version for forward compatibility
    version: z.literal("1.0"),

    // When the report was generated (ISO 8601)
    timestamp: z.string().datetime(),

    // PR metadata
    pr_number: z.number().int().positive(),
    branch: z.string().min(1),
    commit: z.string().regex(/^[a-f0-9]{40}$/, "Must be a full SHA"),

    // GitHub Actions metadata
    workflow_run_id: z.number().int().positive(),

    // Staging environment details
    staging_port: z.number().int().min(4431).max(4530).optional(),
    db_initialized: z.boolean().optional(),

    // Overall result
    passed: z.boolean(),

    // Per-step status tracking
    steps: StagingSteps,
});

// Export inferred TypeScript type
export type StagingReport = z.infer<typeof StagingReportV1>;
export type StepOutcomeType = z.infer<typeof StepOutcome>;

/**
 * Validate a staging report JSON
 * @param json - Parsed JSON object
 * @returns Validated StagingReport or throws ZodError
 */
export function validateStagingReport(json: unknown): StagingReport {
    return StagingReportV1.parse(json);
}

/**
 * Safely validate a staging report JSON
 * @param json - Parsed JSON object
 * @returns { success: true, data: StagingReport } or { success: false, error: ZodError }
 */
export function safeParseStagingReport(json: unknown) {
    return StagingReportV1.safeParse(json);
}
