/**
 * Staging Report Schema
 * 
 * Defines the structure of staging reports generated by stage-react.yml.
 * Version changes should be documented and schema updated accordingly.
 */

import { z } from "zod";

// Step outcome enum (matches GitHub Actions step outcomes)
const StepOutcome = z.enum(["success", "failure", "cancelled", "skipped"]);

// Workflow steps that are tracked for failure detection
const WorkflowStep = z.enum([
    "validate_environment",
    "checkout",
    "prepare_staging_dir",
    "sanity_check",
    "validate_migrations",
    "clone_database",
    "install_deps",
    "backup_db",
    "apply_migrations",
    "build",
    "find_port",
    "start_server",
    "initialize",
    "health_check",
    "e2e_tests",
]);

/**
 * E2E Test Results
 * 
 * Only E2E tests are tracked individually since they use continue-on-error
 * and their outcome can vary. Other steps cause immediate workflow failure.
 */
const E2ETestResult = z.object({
    outcome: StepOutcome,
});

/**
 * Staging Report Schema v1.0
 * 
 * Generated by: .github/workflows/stage-react.yml
 * Consumed by: /wip-stage workflow monitoring
 * 
 * Each step sets CURRENT_STEP before running. If the workflow fails,
 * CURRENT_STEP indicates which step failed. If all steps pass,
 * failed_at_step will be null.
 */
export const StagingReportV1 = z.object({
    // Schema version for forward compatibility
    version: z.literal("1.0"),

    // When the report was generated (ISO 8601)
    timestamp: z.string().datetime(),

    // PR metadata
    pr_number: z.number().int().positive(),
    branch: z.string().min(1),
    commit: z.string().regex(/^[a-f0-9]{40}$/, "Must be a full SHA"),

    // GitHub Actions metadata
    workflow_run_id: z.number().int().positive(),

    // Staging environment details
    staging_port: z.number().int().min(4431).max(4530).optional(),
    db_initialized: z.boolean().optional(),

    // Failure tracking
    // If workflow reached report generation, this is null (all steps passed)
    // Otherwise, indicates which step was running when failure occurred
    failed_at_step: WorkflowStep.nullable(),

    // Last step that completed successfully
    last_completed_step: WorkflowStep.nullable(),

    // Overall result (true if all steps including E2E passed)
    passed: z.boolean(),

    // E2E test outcome (only step that can fail without stopping workflow)
    e2e_tests: E2ETestResult,
});

// Export inferred TypeScript type
export type StagingReport = z.infer<typeof StagingReportV1>;
export type StepOutcomeType = z.infer<typeof StepOutcome>;
export type WorkflowStepType = z.infer<typeof WorkflowStep>;

/**
 * Validate a staging report JSON
 * @param json - Parsed JSON object
 * @returns Validated StagingReport or throws ZodError
 */
export function validateStagingReport(json: unknown): StagingReport {
    return StagingReportV1.parse(json);
}

/**
 * Safely validate a staging report JSON
 * @param json - Parsed JSON object
 * @returns { success: true, data: StagingReport } or { success: false, error: ZodError }
 */
export function safeParseStagingReport(json: unknown) {
    return StagingReportV1.safeParse(json);
}
