-- ============================================================================
-- 007_calendar.sql - Calendar Events
-- ============================================================================
-- Full data extracted from events.toml (47 events)

CREATE TABLE IF NOT EXISTS calendar_events (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    start_time TEXT NOT NULL,  -- ISO 8601
    end_time TEXT NOT NULL,    -- ISO 8601
    all_day INTEGER DEFAULT 0,
    event_type TEXT,
    recurrence TEXT CHECK(recurrence IN ('none', 'daily', 'weekly', 'biweekly', 'monthly', 'yearly') OR recurrence IS NULL),
    recurrence_interval INTEGER DEFAULT 1,
    recurrence_days TEXT,      -- JSON array of day names
    recurrence_until TEXT,     -- ISO 8601 date
    organizer_id TEXT REFERENCES personnel(id),
    location TEXT,
    virtual_url TEXT,
    timezone TEXT DEFAULT 'America/New_York'
);

CREATE TABLE IF NOT EXISTS calendar_participants (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id TEXT NOT NULL REFERENCES calendar_events(id),
    person_id TEXT NOT NULL REFERENCES personnel(id),
    status TEXT DEFAULT 'pending' CHECK(status IN ('pending', 'accepted', 'declined', 'tentative')),
    UNIQUE(event_id, person_id)
);

-- ============================================================================
-- DATA: Calendar Events (47 entries from events.toml)
-- ============================================================================

INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-001', 'Engineering Daily Standup', 'Daily sync for the engineering team to discuss progress and blockers', '2025-01-06T09:00:00', '2025-01-06T09:15:00', 0, 'standup', 'weekly', 1, '["Mon","Tue","Wed","Thu","Fri"]', '2026-06-30', 'd827cb', 'Conference Room 2A', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-002', 'IT Team Weekly', 'Weekly status updates and planning for IT department', '2025-01-07T10:00:00', '2025-01-07T11:00:00', 0, 'meeting', 'weekly', 1, '["Tue"]', '2026-06-30', '1ea074', 'IT Help Desk', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-003', 'Sales Region Sync', 'Weekly sync across all regional sales managers', '2025-01-08T14:00:00', '2025-01-08T15:00:00', 0, 'meeting', 'weekly', 1, '["Wed"]', '2026-06-30', '1e4e5c', NULL, 'https://meet.mmc.com/sales-sync', 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-004', 'HR Office Hours', 'Open door hours for employee questions and concerns', '2025-01-09T13:00:00', '2025-01-09T14:00:00', 0, 'meeting', 'weekly', 1, '["Thu"]', '2026-06-30', '4f6f43', 'HR Suite', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-005', 'Executive Leadership Meeting', 'Bi-weekly leadership sync on company strategy and operations', '2025-01-13T09:00:00', '2025-01-13T10:30:00', 0, 'planning', 'weekly', 2, '["Mon"]', '2026-06-30', '241a6d', 'Board Room', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-006', 'Engineering Sprint Review', 'Bi-weekly review of completed work and demo of new features', '2025-01-17T15:00:00', '2025-01-17T16:30:00', 0, 'review', 'weekly', 2, '["Fri"]', '2026-06-30', 'd827cb', 'Engineering Open Plan', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-007', 'MMC All-Hands Meeting', 'Monthly company-wide meeting with updates from leadership', '2025-01-15T16:00:00', '2025-01-15T17:00:00', 0, 'all-hands', 'monthly', 1, NULL, '2026-06-30', '241a6d', NULL, 'https://meet.mmc.com/all-hands', 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-008', 'Finance Month-End Review', 'Monthly financial close review and analysis', '2025-01-31T10:00:00', '2025-01-31T11:30:00', 0, 'review', 'monthly', 1, NULL, '2026-06-30', 'cdb964', 'Finance Department', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-009', 'Board of Directors Meeting', 'Quarterly board meeting (occurs monthly in seed for demo)', '2025-01-20T09:00:00', '2025-01-20T12:00:00', 0, 'meeting', 'monthly', 3, NULL, '2026-06-30', '241a6d', 'Board Room', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-010', 'Richard / Mike 1:1', 'Weekly one-on-one between CTO and IT Director', '2025-01-06T14:00:00', '2025-01-06T14:30:00', 0, '1:1', 'weekly', 1, '["Mon"]', '2026-06-30', '714fd4', 'Executive Suite', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-011', 'David / Jennifer 1:1', 'Weekly one-on-one for career development and project updates', '2025-01-07T11:00:00', '2025-01-07T11:30:00', 0, '1:1', 'weekly', 1, '["Tue"]', '2026-06-30', 'd827cb', NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-012', 'New Employee Orientation', 'Orientation session for Q1 2025 new hires', '2025-01-20T09:00:00', '2025-01-20T12:00:00', 0, 'training', NULL, NULL, NULL, NULL, '4f6f43', 'HR Suite', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-013', 'Cybersecurity Awareness Training', 'Annual security training for all employees', '2025-02-15T13:00:00', '2025-02-15T15:00:00', 0, 'training', NULL, NULL, NULL, NULL, '1ea074', NULL, 'https://training.mmc.com/security-2025', 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-014', 'Product Design Workshop', 'Collaborative workshop on next-gen HVAC product design', '2025-03-10T09:00:00', '2025-03-10T16:00:00', 0, 'training', NULL, NULL, NULL, NULL, 'd827cb', 'CAD Lab', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-015', 'Leadership Development Program - Session 1', 'First session of 2025 leadership development series', '2025-04-05T09:00:00', '2025-04-05T17:00:00', 0, 'training', NULL, NULL, NULL, NULL, '4f6f43', 'Board Room', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-016', 'HVAC Industry Conference', 'Annual industry conference in Chicago', '2025-05-12T08:00:00', '2025-05-14T18:00:00', 1, 'conference', NULL, NULL, NULL, NULL, '714fd4', NULL, NULL, 'America/Chicago');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-017', 'Customer Summit 2025', 'Annual customer appreciation and product showcase event', '2025-09-18T09:00:00', '2025-09-19T17:00:00', 1, 'conference', NULL, NULL, NULL, NULL, '241a6d', 'Reception Area', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-018', 'New Year''s Day', 'Company Holiday - Office Closed', '2025-01-01T00:00:00', '2025-01-01T23:59:59', 1, 'holiday', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-019', 'Martin Luther King Jr. Day', 'Company Holiday - Office Closed', '2025-01-20T00:00:00', '2025-01-20T23:59:59', 1, 'holiday', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-020', 'Presidents Day', 'Company Holiday - Office Closed', '2025-02-17T00:00:00', '2025-02-17T23:59:59', 1, 'holiday', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-021', 'Memorial Day', 'Company Holiday - Office Closed', '2025-05-26T00:00:00', '2025-05-26T23:59:59', 1, 'holiday', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-022', 'Independence Day', 'Company Holiday - Office Closed', '2025-07-04T00:00:00', '2025-07-04T23:59:59', 1, 'holiday', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-023', 'Labor Day', 'Company Holiday - Office Closed', '2025-09-01T00:00:00', '2025-09-01T23:59:59', 1, 'holiday', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-024', 'Thanksgiving', 'Company Holiday - Office Closed', '2025-11-27T00:00:00', '2025-11-28T23:59:59', 1, 'holiday', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-025', 'Christmas Holiday', 'Company Holiday - Office Closed', '2025-12-24T00:00:00', '2025-12-26T23:59:59', 1, 'holiday', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-026', 'New Year''s Day 2026', 'Company Holiday - Office Closed', '2026-01-01T00:00:00', '2026-01-01T23:59:59', 1, 'holiday', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-027', 'ERP System Upgrade Kickoff', 'Kickoff meeting for the 2025 ERP system upgrade project', '2025-02-03T10:00:00', '2025-02-03T12:00:00', 0, 'planning', NULL, NULL, NULL, NULL, '1ea074', 'IT Help Desk', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-028', 'Q1 2025 Business Review', 'Quarterly business review and planning session', '2025-04-07T09:00:00', '2025-04-07T16:00:00', 0, 'review', NULL, NULL, NULL, NULL, '241a6d', 'Board Room', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-029', 'Q2 2025 Business Review', 'Quarterly business review and planning session', '2025-07-07T09:00:00', '2025-07-07T16:00:00', 0, 'review', NULL, NULL, NULL, NULL, '241a6d', 'Board Room', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-030', '2026 Strategic Planning Session', 'Annual strategic planning workshop for 2026', '2025-11-10T09:00:00', '2025-11-11T17:00:00', 1, 'planning', NULL, NULL, NULL, NULL, '241a6d', 'Board Room', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-031', 'Interview Block - Engineering', 'Reserved time for engineering candidate interviews', '2025-01-10T14:00:00', '2025-01-10T16:00:00', 0, 'interview', 'weekly', 2, '["Fri"]', '2026-06-30', 'd827cb', 'Conference Room 2A', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-032', 'Architecture Review - Q4 Systems', 'Quarterly architecture review session - overlaps with Interview Block and Sprint Review for 3-lane layout testing', '2025-12-19T14:30:00', '2025-12-19T15:30:00', 0, 'review', NULL, NULL, NULL, NULL, '714fd4', 'Engineering Open Plan', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-033', 'Benefits Enrollment Meeting', 'One-on-one meeting to review and select 2025 benefits', '2025-01-14T10:00:00', '2025-01-14T10:30:00', 0, 'appointment', NULL, NULL, NULL, NULL, '4f6f43', 'HR Suite', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-034', 'Annual Physical - Company Wellness', 'Annual health screening as part of company wellness program', '2025-02-20T08:30:00', '2025-02-20T09:30:00', 0, 'appointment', NULL, NULL, NULL, NULL, '4f6f43', 'Medical Wing', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-035', 'Performance Review - Lisa Chen', 'Annual performance review meeting', '2025-03-17T14:00:00', '2025-03-17T15:00:00', 0, 'appointment', NULL, NULL, NULL, NULL, 'd827cb', 'Conference Room 2A', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-036', 'Submit Expense Reports', 'Reminder: Monthly expense reports due by end of day', '2025-01-31T09:00:00', '2025-01-31T09:30:00', 0, 'reminder', 'monthly', 1, NULL, '2026-06-30', NULL, NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-037', '401k Contribution Review', 'Reminder to review and update 401k contribution elections', '2025-04-01T09:00:00', '2025-04-01T09:30:00', 0, 'reminder', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-038', 'Q1 Goals Check-in', 'Reminder: Review Q1 goals progress before monthly review', '2025-03-25T09:00:00', '2025-03-25T09:30:00', 0, 'reminder', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-039', 'David Park - PTO', 'Vacation - Will return January 8th', '2025-01-02T00:00:00', '2025-01-07T23:59:59', 1, 'out-of-office', NULL, NULL, NULL, NULL, 'd827cb', NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-040', 'Jennifer Adams - Conference Travel', 'Attending HVAC Industry Conference in Chicago', '2025-05-11T00:00:00', '2025-05-15T23:59:59', 1, 'out-of-office', NULL, NULL, NULL, NULL, 'f9c8d7', NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-041', 'Mike Chen - Working Remote', 'Working from home - Available via Slack/Teams', '2025-02-24T00:00:00', '2025-02-28T23:59:59', 1, 'out-of-office', NULL, NULL, NULL, NULL, '1ea074', NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-042', 'Margaret Sullivan - Board Meeting Travel', 'Traveling for quarterly board meeting in NYC', '2025-04-14T00:00:00', '2025-04-16T23:59:59', 1, 'out-of-office', NULL, NULL, NULL, NULL, 'cdb964', NULL, NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-043', 'Year-End Team Celebration', 'Holiday party and team celebration for 2024', '2024-12-13T15:00:00', '2024-12-13T18:00:00', 0, 'meeting', NULL, NULL, NULL, NULL, '241a6d', 'Reception Area', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-044', 'Engineering Standup', 'Daily sync for the engineering team', '2024-12-12T09:00:00', '2024-12-12T09:15:00', 0, 'standup', 'weekly', 1, '["Mon","Tue","Wed","Thu","Fri"]', '2024-12-31', 'd827cb', 'Conference Room 2A', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-045', 'Q4 2024 Business Review', 'Final quarterly business review for 2024', '2024-12-16T09:00:00', '2024-12-16T16:00:00', 0, 'review', NULL, NULL, NULL, NULL, '241a6d', 'Board Room', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-046', 'IT Year-End Security Audit', 'Annual security compliance review before year end', '2024-12-18T10:00:00', '2024-12-18T12:00:00', 0, 'review', NULL, NULL, NULL, NULL, '1ea074', 'IT Help Desk', NULL, 'America/New_York');
INSERT INTO calendar_events (id, title, description, start_time, end_time, all_day, event_type, recurrence, recurrence_interval, recurrence_days, recurrence_until, organizer_id, location, virtual_url, timezone) VALUES ('evt-047', 'Holiday Office Closure', 'Office closed for winter holidays', '2024-12-23T00:00:00', '2024-12-31T23:59:59', 1, 'holiday', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'America/New_York');
