// Import and initialize the ui-app WASM module
// This will be generated by trunk build of ui-app

import init from './ui_app.js';

// Initialize the WASM app
init().then(() => {
    console.log('WASM app initialized');
}).catch((error) => {
    console.error('Failed to initialize WASM app:', error);
});
