//! Input Component Scaffold
//!
//! AUTO-GENERATED by rubigo-build - LLM fills in implementation
//!
//! This is a scaffold with method stubs. Run tests and iterate until passing.

use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;

/// Input context - the extended state (internal, not exposed to JS)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct InputContext {
    /// Current input text
    pub value: String,
    /// Whether input is disabled
    pub disabled: bool,
    /// Whether input is read-only
    pub read_only: bool,
    /// Whether input has focus
    pub focused: bool,
    /// Error message (empty = no error)
    pub error: String,
}

impl InputContext {
    pub fn new() -> Self {
        Self {
            value: "".to_string(),
            disabled: false,
            read_only: false,
            focused: false,
            error: "".to_string(),
        }
    }
}

/// Input component
#[wasm_bindgen]
pub struct Input {
    context: InputContext,
    state: String,
}

#[wasm_bindgen]
impl Input {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self {
            context: InputContext::new(),
            state: "idle".to_string(),
        }
    }

    // === Getters ===

    #[wasm_bindgen(getter)]
    pub fn state_name(&self) -> String {
        self.state.clone()
    }

    /// Get context as JSON string (for JS interop)
    #[wasm_bindgen(getter)]
    pub fn context_json(&self) -> String {
        serde_json::to_string(&self.context).unwrap_or_default()
    }

    // === Actions ===

    pub fn set_focused(&mut self) -> bool {
        if self.context.disabled {
            return false;
        }
        self.context.focused = true;
        self.state = "focused".to_string();
        true
    }

    pub fn clear_focused(&mut self) -> bool {
        self.context.focused = false;
        self.state = "idle".to_string();
        true
    }

    pub fn set_value(&mut self) -> bool {
        if self.context.disabled || self.context.read_only {
            return false;
        }
        // In real usage, would take payload.value
        // For conformance test, just return true
        true
    }
}

impl Default for Input {
    fn default() -> Self {
        Self::new()
    }
}

// === Test Module ===
// Tests are in a separate file for clean separation
#[cfg(test)]
#[path = "tests.rs"]
mod tests;

fn main() {}
