-- FEATURES
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'f01a23', 'Real-time Technician Tracking', 'GPS-enabled tracking of field technicians for optimal dispatch', '101a2b', 'in_progress');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'f02b34', 'Predictive Parts Inventory', 'ML-based prediction of required parts for common equipment issues', '202b3c', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'f03c45', 'Customer Portal', 'Self-service portal for service requests, status tracking, and feedback', '303c4d', 'in_progress');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-personnel-crud', 'Personnel CRUD Operations', 'Create, read, update, delete capabilities for personnel records', 'obj-rubigo-personnel', 'in_progress');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-calendar-crud', 'Calendar Event CRUD', 'Create, read, update, delete calendar events with full event details', 'obj-calendar-core', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-calendar-recurrence', 'Recurring Event Management', 'Support for daily, weekly, monthly, yearly recurrence with instance deviations', 'obj-calendar-recurrence', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-calendar-views', 'Calendar View Modes', 'Month view grid, week view, and day view with time slots', 'obj-calendar-views', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-calendar-navigation', 'Calendar Navigation', 'Navigate between months/weeks, jump to today, work week toggle', 'obj-calendar-views', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-calendar-participants', 'Event Participants', 'Assign organizers and participants to events', 'obj-calendar-core', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-calendar-timezone', 'Event Timezone Management', 'Select event timezone and display local time conversion when event timezone differs from user''s local timezone', 'obj-calendar-core', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-calendar-day-view', 'Day View Mode', 'Single day view with hourly time slots for detailed daily schedule', 'obj-calendar-views', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-calendar-all-day', 'All Day Events', 'Mark events as all-day to display without specific times', 'obj-calendar-core', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-calendar-overlap', 'Overlapping Event Display', 'Display overlapping events side-by-side in day and week views with proper lane assignment', 'obj-calendar-views', 'in_progress');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-calendar-current-time', 'Current Time Indicator', 'Display a real-time indicator showing the current time in Day view, automatically updating without page refresh', 'obj-calendar-views', 'in_progress');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-email-compose', 'Email Composition', 'Compose and send messages to personnel or custom email addresses with plain text body', 'obj-email-core', 'in_progress');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-email-recipients', 'Recipient Selection', 'Select recipients from personnel directory or enter custom email addresses', 'obj-email-core', 'in_progress');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-email-inbox', 'Email Inbox', 'View received messages with sender, subject, preview, and timestamp', 'obj-email-core', 'in_progress');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-email-reading', 'Email Reading', 'View full email content with sender info, timestamp, and message body', 'obj-email-core', 'in_progress');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-email-thread', 'Email Threading', 'View and reply to message threads/conversations with full context', 'obj-email-threading', 'in_progress');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-email-folders', 'Email Folders', 'Organize messages in Inbox, Sent, Drafts, and Trash folders', 'obj-email-organization', 'in_progress');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-email-search', 'Email Search', 'Search messages by sender, subject, and content', 'obj-email-organization', 'in_progress');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-chat-dm', 'Direct Messages', 'One-on-one messaging between users', 'obj-chat-core', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-chat-channels', 'Chat Channels', 'Group conversations organized by topic or team', 'obj-chat-core', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-chat-messages', 'Message Composition', 'Send messages with text, emoji, and formatting', 'obj-chat-core', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-chat-reactions', 'Message Reactions', 'React to messages with emoji', 'obj-chat-engagement', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-chat-threads', 'Threaded Replies', 'Reply to specific messages in a thread', 'obj-chat-engagement', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-chat-presence', 'User Presence', 'See online/offline status of colleagues', 'obj-chat-core', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-screenshare-start', 'Screen Share Session', 'Start and stop screen sharing with selected participants', 'obj-screenshare-core', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-screenshare-view', 'Screen Share Viewer', 'View shared screens from other users', 'obj-screenshare-core', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-screenshare-chat', 'Screen Share from Chat', 'Initiate screen sharing directly from a chat conversation', 'obj-screenshare-core', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-aco-schema', 'Access Control Object Schema', 'Every data table has an ACO (indexed JSON) and SCO (metadata JSON) column for access control', 'obj-rubigo-access', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-sensitivity-levels', 'Sensitivity Level Enforcement', 'Users can only access data with sensitivity at or below their clearance level', 'obj-rubigo-sensitivity', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-tenant-access', 'Tenant Compartment Enforcement', 'Users can only access data in tenants they have been granted access to at the appropriate level', 'obj-rubigo-tenants', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-role-requirements', 'Role Requirement Enforcement', 'Users must have all required roles to access data that specifies role requirements', 'obj-rubigo-roles', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-access-logging', 'Access Logging', 'All data access operations are logged with full context for audit purposes', 'obj-rubigo-audit', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-classification-guides', 'Classification Guide Management', 'Administrators can create and manage classification guides that provide English-level descriptions of how to classify data', 'obj-rubigo-classification', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-aco-modification', 'ACO Modification', 'Users can modify the access control settings of records they can access, within their clearance limits', 'obj-rubigo-access', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-mcp-server', 'MCP Server Integration', 'Model Context Protocol server that exposes Rubigo data entities as resources and provides tools for CRUD operations, enabling AI agents and LLM-based tools to interact with the platform', 'obj-rubigo-integration', 'planned');

INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-calendar-orphan-deviations', 'Orphaned Deviation Management', 'View and delete orphaned deviations from recurring events when pattern changes leave modifications/cancellations targeting dates that no longer occur', 'obj-calendar-recurrence', 'in_progress');

INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-mcp-action-source', 'MCP Action Source Identification', 'Action logs distinguish MCP-originated operations from UI and API calls', 'obj-rubigo-audit', 'planned');

-- ANALYTICS AND OBSERVABILITY (GH #33)
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-analytics-collection', 'Telemetry Collection', 'Automatic collection of page views, feature events, and session data via useAnalytics hook', 'obj-rubigo-metrics', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-analytics-otel', 'OpenTelemetry Instrumentation', 'Automatic span collection for HTTP requests, SSR, API routes, and DB queries via @vercel/otel', 'obj-rubigo-metrics', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-analytics-vitals', 'Web Vitals Collection', 'Automatic collection of Core Web Vitals (LCP, FCP, TTFB, CLS, INP) via useReportWebVitals', 'obj-rubigo-metrics', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-analytics-duckdb', 'DuckDB Analytical Queries', 'Read-only DuckDB attachment to SQLite for OLAP queries on telemetry data', 'obj-rubigo-metrics', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-analytics-warehouse', 'Parquet Warehousing', 'ETL process to archive old telemetry to Parquet files for historical analysis', 'obj-rubigo-metrics', 'planned');
INSERT INTO features (profile_id, id, name, description, objective_id, status) VALUES ('mmc', 'feat-analytics-dashboard', 'Analytics Discovery Dashboard', 'Admin-only /analytics route with overview, performance, and usage views', 'obj-rubigo-metrics', 'planned');
