//! Collapsible Component Scaffold
//!
//! AUTO-GENERATED by rubigo-build - LLM fills in implementation
//!
//! This is a scaffold with method stubs. Run tests and iterate until passing.

use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;

/// Collapsible context - the extended state (internal, not exposed to JS)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct CollapsibleContext {
    /// Whether content is expanded
    pub open: bool,
    /// Whether interaction is blocked
    pub disabled: bool,
}

impl CollapsibleContext {
    pub fn new() -> Self {
        Self {
            open: false,
            disabled: false,
        }
    }
}

/// Collapsible component
#[wasm_bindgen]
pub struct Collapsible {
    context: CollapsibleContext,
    state: String,
}

#[wasm_bindgen]
impl Collapsible {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self {
            context: CollapsibleContext::new(),
            state: "idle".to_string(),
        }
    }

    // === Getters ===

    #[wasm_bindgen(getter)]
    pub fn state_name(&self) -> String {
        self.state.clone()
    }

    /// Get context as JSON string (for JS interop)
    #[wasm_bindgen(getter)]
    pub fn context_json(&self) -> String {
        serde_json::to_string(&self.context).unwrap_or_default()
    }

    // === Actions ===

    /// Expand the content panel
    pub fn expand(&mut self) -> bool {
        // Mutation: context.open = true
        // Emits: ["onOpenChange"]
        if self.context.disabled {
            return false;
        }
        self.context.open = true;
        self.state = "expanded".to_string();
        true // Would trigger onOpenChange callback in JS
    }

    /// Collapse the content panel
    pub fn collapse(&mut self) -> bool {
        // Mutation: context.open = false
        // Emits: ["onOpenChange"]
        if self.context.disabled {
            return false;
        }
        self.context.open = false;
        self.state = "collapsed".to_string();
        true // Would trigger onOpenChange callback in JS
    }
}

impl Default for Collapsible {
    fn default() -> Self {
        Self::new()
    }
}

// === Test Module ===
// Tests are in a separate file for clean separation
#[cfg(test)]
#[path = "tests.rs"]
mod tests;

fn main() {}
