/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all services
         * @description Returns all products and services in the portfolio
         */
        get: operations["listServices"];
        put?: never;
        /** Create a new service */
        post: operations["createService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        /** Get a service by ID */
        get: operations["getService"];
        put?: never;
        post?: never;
        /** Delete a service */
        delete: operations["deleteService"];
        options?: never;
        head?: never;
        /** Update a service */
        patch: operations["updateService"];
        trace?: never;
    };
    "/objectives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all objectives */
        get: operations["listObjectives"];
        put?: never;
        /** Create a new objective */
        post: operations["createObjective"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objectives/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        /** Get an objective by ID */
        get: operations["getObjective"];
        put?: never;
        post?: never;
        /** Delete an objective */
        delete: operations["deleteObjective"];
        options?: never;
        head?: never;
        /** Update an objective */
        patch: operations["updateObjective"];
        trace?: never;
    };
    "/objectives/{id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        /**
         * Get child objectives
         * @description Returns immediate children of the specified objective
         */
        get: operations["getObjectiveChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objectives/{id}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        /**
         * Get full objective tree
         * @description Returns the objective and all descendants as a tree structure
         */
        get: operations["getObjectiveTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all projects */
        get: operations["listProjects"];
        put?: never;
        /** Create a new project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        /** Get a project by ID */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Delete a project */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Update a project */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all features */
        get: operations["listFeatures"];
        put?: never;
        /** Create a new feature */
        post: operations["createFeature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        get: operations["getFeature"];
        put?: never;
        post?: never;
        delete: operations["deleteFeature"];
        options?: never;
        head?: never;
        patch: operations["updateFeature"];
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all metrics */
        get: operations["listMetrics"];
        put?: never;
        post: operations["createMetric"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        get: operations["getMetric"];
        put?: never;
        post?: never;
        delete: operations["deleteMetric"];
        options?: never;
        head?: never;
        patch: operations["updateMetric"];
        trace?: never;
    };
    "/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all KPIs */
        get: operations["listKPIs"];
        put?: never;
        post: operations["createKPI"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kpis/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        get: operations["getKPI"];
        put?: never;
        post?: never;
        delete: operations["deleteKPI"];
        options?: never;
        head?: never;
        patch: operations["updateKPI"];
        trace?: never;
    };
    "/initiatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInitiatives"];
        put?: never;
        post: operations["createInitiative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/initiatives/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        get: operations["getInitiative"];
        put?: never;
        post?: never;
        delete: operations["deleteInitiative"];
        options?: never;
        head?: never;
        patch: operations["updateInitiative"];
        trace?: never;
    };
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listActivities"];
        put?: never;
        post: operations["createActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        get: operations["getActivity"];
        put?: never;
        post?: never;
        delete: operations["deleteActivity"];
        options?: never;
        head?: never;
        patch: operations["updateActivity"];
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoles"];
        put?: never;
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        get: operations["getRole"];
        put?: never;
        post?: never;
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch: operations["updateRole"];
        trace?: never;
    };
    "/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssignments"];
        put?: never;
        post: operations["createAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        get: operations["getAssignment"];
        put?: never;
        post?: never;
        delete: operations["deleteAssignment"];
        options?: never;
        head?: never;
        patch: operations["updateAssignment"];
        trace?: never;
    };
    "/allocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAllocations"];
        put?: never;
        post: operations["createAllocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        get: operations["getAllocation"];
        put?: never;
        post?: never;
        delete: operations["deleteAllocation"];
        options?: never;
        head?: never;
        patch: operations["updateAllocation"];
        trace?: never;
    };
    "/bulk/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export all project data
         * @description Export all entities in TOML format
         */
        get: operations["exportAllData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulk/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import project data
         * @description Import entities from TOML or JSON format
         */
        post: operations["importAllData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code?: string;
            message?: string;
            details?: Record<string, never>;
        };
        PaginationMeta: {
            total?: number;
            limit?: number;
            offset?: number;
        };
        Service: {
            id: string;
            name: string;
            description?: string;
            /** @enum {string} */
            status: "pipeline" | "catalog" | "retired";
            is_product?: boolean;
            is_service?: boolean;
        };
        ServiceInput: {
            name: string;
            description?: string;
            /**
             * @default pipeline
             * @enum {string}
             */
            status: "pipeline" | "catalog" | "retired";
            /** @default false */
            is_product: boolean;
            /** @default true */
            is_service: boolean;
        };
        ServiceUpdate: {
            name?: string;
            description?: string;
            /** @enum {string} */
            status?: "pipeline" | "catalog" | "retired";
            is_product?: boolean;
            is_service?: boolean;
        };
        ServiceList: {
            data?: components["schemas"]["Service"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Project: {
            id: string;
            name: string;
            description?: string;
            service_id: string;
            /** @enum {string} */
            status: "planning" | "active" | "on_hold" | "complete" | "cancelled";
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
        };
        ProjectInput: {
            name: string;
            description?: string;
            service_id: string;
            /** @default planning */
            status: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
        };
        ProjectUpdate: {
            name?: string;
            description?: string;
            status?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
        };
        ProjectList: {
            data?: components["schemas"]["Project"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Objective: {
            id: string;
            title: string;
            description?: string;
            project_id: string;
            parent_id?: string;
            /** @enum {string} */
            status: "draft" | "active" | "achieved" | "deferred";
        };
        ObjectiveInput: {
            title: string;
            description?: string;
            project_id: string;
            parent_id?: string;
            /** @default draft */
            status: string;
        };
        ObjectiveUpdate: {
            title?: string;
            description?: string;
            parent_id?: string;
            status?: string;
        };
        ObjectiveList: {
            data?: components["schemas"]["Objective"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        ObjectiveTree: components["schemas"]["Objective"] & {
            children?: components["schemas"]["ObjectiveTree"][];
            features?: components["schemas"]["Feature"][];
            kpis?: components["schemas"]["KPIWithMetric"][];
        };
        Feature: {
            id: string;
            name: string;
            description?: string;
            objective_id: string;
            /** @enum {string} */
            status?: "planned" | "in_progress" | "complete" | "cancelled";
        };
        FeatureInput: {
            name: string;
            description?: string;
            objective_id: string;
            /** @default planned */
            status: string;
        };
        FeatureUpdate: {
            name?: string;
            description?: string;
            status?: string;
        };
        FeatureList: {
            data?: components["schemas"]["Feature"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Metric: {
            id: string;
            name: string;
            description?: string;
            unit: string;
            current_value?: number;
            source?: string;
        };
        MetricInput: {
            name: string;
            description?: string;
            unit: string;
            current_value?: number;
            source?: string;
        };
        MetricUpdate: {
            name?: string;
            description?: string;
            unit?: string;
            current_value?: number;
            source?: string;
        };
        MetricList: {
            data?: components["schemas"]["Metric"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        KPI: {
            id: string;
            metric_id: string;
            objective_id?: string;
            target_value: number;
            /** @enum {string} */
            direction: "increase" | "decrease" | "maintain";
            threshold_warning?: number;
            threshold_critical?: number;
        };
        KPIInput: {
            metric_id: string;
            objective_id?: string;
            target_value: number;
            /** @enum {string} */
            direction: "increase" | "decrease" | "maintain";
            threshold_warning?: number;
            threshold_critical?: number;
        };
        KPIUpdate: {
            objective_id?: string;
            target_value?: number;
            direction?: string;
            threshold_warning?: number;
            threshold_critical?: number;
        };
        KPIWithMetric: components["schemas"]["KPI"] & {
            metric?: components["schemas"]["Metric"];
            objective?: components["schemas"]["Objective"];
            current_value?: number;
            percent_complete?: number;
        };
        KPIList: {
            data?: components["schemas"]["KPI"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Initiative: {
            id: string;
            name: string;
            description?: string;
            kpi_id: string;
            /** @enum {string} */
            status?: "planned" | "active" | "complete" | "cancelled";
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
        };
        InitiativeInput: {
            name: string;
            description?: string;
            kpi_id: string;
            /** @default planned */
            status: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
        };
        InitiativeUpdate: {
            name?: string;
            description?: string;
            status?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
        };
        InitiativeList: {
            data?: components["schemas"]["Initiative"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Activity: {
            id: string;
            name: string;
            description?: string;
            parent_id?: string;
            initiative_id?: string;
            blocked_by?: string[];
            /** @enum {string} */
            status?: "backlog" | "ready" | "in_progress" | "blocked" | "complete";
        };
        ActivityInput: {
            name: string;
            description?: string;
            parent_id?: string;
            initiative_id?: string;
            blocked_by?: string[];
            /** @default backlog */
            status: string;
        };
        ActivityUpdate: {
            name?: string;
            description?: string;
            parent_id?: string;
            initiative_id?: string;
            blocked_by?: string[];
            status?: string;
        };
        ActivityList: {
            data?: components["schemas"]["Activity"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Role: {
            id: string;
            name: string;
            description?: string;
        };
        RoleInput: {
            name: string;
            description?: string;
        };
        RoleUpdate: {
            name?: string;
            description?: string;
        };
        RoleList: {
            data?: components["schemas"]["Role"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Assignment: {
            id: string;
            activity_id: string;
            role_id: string;
            quantity: number;
            /** @default fte */
            unit: string;
            /** @enum {string} */
            raci_type?: "responsible" | "accountable" | "consulted" | "informed";
        };
        AssignmentInput: {
            activity_id: string;
            role_id: string;
            quantity: number;
            /** @default fte */
            unit: string;
            /** @default responsible */
            raci_type: string;
        };
        AssignmentUpdate: {
            quantity?: number;
            unit?: string;
            raci_type?: string;
        };
        AssignmentWithCapacity: components["schemas"]["Assignment"] & {
            role?: components["schemas"]["Role"];
            activity?: components["schemas"]["Activity"];
            allocations?: components["schemas"]["Allocation"][];
            total_allocated?: number;
            /** @description Positive = under-resourced, negative = over-resourced */
            capacity_gap?: number;
        };
        AssignmentList: {
            data?: components["schemas"]["Assignment"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        Allocation: {
            id: string;
            assignment_id: string;
            person_id: string;
            quantity_contributed: number;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
        };
        AllocationInput: {
            assignment_id: string;
            person_id: string;
            quantity_contributed: number;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
        };
        AllocationUpdate: {
            quantity_contributed?: number;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
        };
        AllocationList: {
            data?: components["schemas"]["Allocation"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Entity not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Entity ID */
        idParam: string;
        limitParam: number;
        offsetParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listServices: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limitParam"];
                offset?: components["parameters"]["offsetParam"];
                /** @description Filter by product flag */
                is_product?: boolean;
                /** @description Filter by service flag */
                is_service?: boolean;
                status?: "pipeline" | "catalog" | "retired";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of services */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceInput"];
            };
        };
        responses: {
            /** @description Service created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Cannot delete - has dependent projects */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceUpdate"];
            };
        };
        responses: {
            /** @description Service updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listObjectives: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limitParam"];
                offset?: components["parameters"]["offsetParam"];
                /** @description Filter by project */
                project_id?: string;
                /** @description Filter by parent objective (use 'null' for root) */
                parent_id?: string;
                status?: "draft" | "active" | "achieved" | "deferred";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of objectives */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectiveList"];
                };
            };
        };
    };
    createObjective: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObjectiveInput"];
            };
        };
        responses: {
            /** @description Objective created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Objective"];
                };
            };
        };
    };
    getObjective: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Objective details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Objective"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteObjective: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Objective deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot delete - has child objectives */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateObjective: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObjectiveUpdate"];
            };
        };
        responses: {
            /** @description Objective updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Objective"];
                };
            };
        };
    };
    getObjectiveChildren: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of child objectives */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectiveList"];
                };
            };
        };
    };
    getObjectiveTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Objective tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectiveTree"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limitParam"];
                offset?: components["parameters"]["offsetParam"];
                service_id?: string;
                status?: "planning" | "active" | "on_hold" | "complete" | "cancelled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Project updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    listFeatures: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limitParam"];
                offset?: components["parameters"]["offsetParam"];
                objective_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of features */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureList"];
                };
            };
        };
    };
    createFeature: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureInput"];
            };
        };
        responses: {
            /** @description Feature created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
        };
    };
    getFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
        };
    };
    deleteFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FeatureUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
        };
    };
    listMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricList"];
                };
            };
        };
    };
    createMetric: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MetricInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metric"];
                };
            };
        };
    };
    getMetric: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metric"];
                };
            };
        };
    };
    deleteMetric: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMetric: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MetricUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metric"];
                };
            };
        };
    };
    listKPIs: {
        parameters: {
            query?: {
                objective_id?: string;
                metric_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPIList"];
                };
            };
        };
    };
    createKPI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KPIInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPI"];
                };
            };
        };
    };
    getKPI: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPIWithMetric"];
                };
            };
        };
    };
    deleteKPI: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateKPI: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KPIUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPI"];
                };
            };
        };
    };
    listInitiatives: {
        parameters: {
            query?: {
                kpi_id?: string;
                status?: "planned" | "active" | "complete" | "cancelled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitiativeList"];
                };
            };
        };
    };
    createInitiative: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["InitiativeInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Initiative"];
                };
            };
        };
    };
    getInitiative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Initiative"];
                };
            };
        };
    };
    deleteInitiative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateInitiative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["InitiativeUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Initiative"];
                };
            };
        };
    };
    listActivities: {
        parameters: {
            query?: {
                initiative_id?: string;
                status?: "backlog" | "ready" | "in_progress" | "blocked" | "complete";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityList"];
                };
            };
        };
    };
    createActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ActivityInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
        };
    };
    getActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
        };
    };
    deleteActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ActivityUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleList"];
                };
            };
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RoleInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    listAssignments: {
        parameters: {
            query?: {
                activity_id?: string;
                role_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentList"];
                };
            };
        };
    };
    createAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AssignmentInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    getAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentWithCapacity"];
                };
            };
        };
    };
    deleteAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AssignmentUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    listAllocations: {
        parameters: {
            query?: {
                assignment_id?: string;
                person_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationList"];
                };
            };
        };
    };
    createAllocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AllocationInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Allocation"];
                };
            };
        };
    };
    getAllocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Allocation"];
                };
            };
        };
    };
    deleteAllocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAllocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity ID */
                id: components["parameters"]["idParam"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AllocationUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Allocation"];
                };
            };
        };
    };
    exportAllData: {
        parameters: {
            query?: {
                format?: "toml" | "json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exported data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/toml": string;
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    importAllData: {
        parameters: {
            query?: {
                /** @description merge = add/update, replace = delete all first */
                mode?: "merge" | "replace";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/toml": string;
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Import complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created?: number;
                        updated?: number;
                        deleted?: number;
                    };
                };
            };
        };
    };
}
