//! Slider Component Scaffold
//!
//! AUTO-GENERATED by rubigo-build - LLM fills in implementation
//!
//! This is a scaffold with method stubs. Run tests and iterate until passing.

use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;

/// Slider context - the extended state (internal, not exposed to JS)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SliderContext {
    /// Current slider value
    pub value: i32,
    /// Minimum value
    pub min: i32,
    /// Maximum value
    pub max: i32,
    /// Step increment
    pub step: i32,
    /// Whether interaction is blocked
    pub disabled: bool,
    /// Whether currently dragging
    pub dragging: bool,
}

impl SliderContext {
    pub fn new() -> Self {
        Self {
            value: 50,
            min: 0,
            max: 100,
            step: 1,
            disabled: false,
            dragging: false,
        }
    }
}

/// Slider component
#[wasm_bindgen]
pub struct Slider {
    context: SliderContext,
    state: String,
}

#[wasm_bindgen]
impl Slider {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self {
            context: SliderContext::new(),
            state: "idle".to_string(),
        }
    }

    // === Getters ===

    #[wasm_bindgen(getter)]
    pub fn state_name(&self) -> String {
        self.state.clone()
    }

    /// Get context as JSON string (for JS interop)
    #[wasm_bindgen(getter)]
    pub fn context_json(&self) -> String {
        serde_json::to_string(&self.context).unwrap_or_default()
    }

    // === Actions ===

    /// Increase value by step, clamped to max
    pub fn increment_value(&mut self) -> bool {
        if self.context.disabled {
            return false;
        }
        self.context.value = (self.context.value + self.context.step).min(self.context.max);
        true
    }

    /// Decrease value by step, clamped to min
    pub fn decrement_value(&mut self) -> bool {
        if self.context.disabled {
            return false;
        }
        self.context.value = (self.context.value - self.context.step).max(self.context.min);
        true
    }

    /// Set value to minimum
    pub fn set_to_min(&mut self) -> bool {
        if self.context.disabled {
            return false;
        }
        self.context.value = self.context.min;
        true
    }

    /// Set value to maximum
    pub fn set_to_max(&mut self) -> bool {
        if self.context.disabled {
            return false;
        }
        self.context.value = self.context.max;
        true
    }

    /// Begin drag interaction
    pub fn start_drag(&mut self) -> bool {
        if self.context.disabled {
            return false;
        }
        self.context.dragging = true;
        self.state = "dragging".to_string();
        true
    }

    /// End drag interaction
    pub fn end_drag(&mut self) -> bool {
        self.context.dragging = false;
        self.state = "idle".to_string();
        true
    }

    /// Update value during drag
    pub fn update_value(&mut self) -> bool {
        // In real usage, would take payload.value
        // For now, just confirm it doesn't panic
        true
    }
}

impl Default for Slider {
    fn default() -> Self {
        Self::new()
    }
}

// === Test Module ===
// Tests are in a separate file for clean separation
#[cfg(test)]
#[path = "tests.rs"]
mod tests;

fn main() {}
