//! Checkbox Component Scaffold
//!
//! AUTO-GENERATED by rubigo-build - LLM fills in implementation
//!
//! This is a scaffold with method stubs. Run tests and iterate until passing.

use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;

/// Checkbox context - the extended state (internal, not exposed to JS)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct CheckboxContext {
    /// Current checked state
    pub checked: bool,
    /// If true, all interactions blocked
    pub disabled: bool,
    /// Tri-state visual (neither checked nor unchecked)
    pub indeterminate: bool,
}

impl CheckboxContext {
    pub fn new() -> Self {
        Self {
            checked: false,
            disabled: false,
            indeterminate: false,
        }
    }
}

/// Checkbox component
#[wasm_bindgen]
pub struct Checkbox {
    context: CheckboxContext,
    state: String,
}

#[wasm_bindgen]
impl Checkbox {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self {
            context: CheckboxContext::new(),
            state: "idle".to_string(),
        }
    }

    // === Getters ===

    #[wasm_bindgen(getter)]
    pub fn state_name(&self) -> String {
        self.state.clone()
    }

    /// Get context as JSON string (for JS interop)
    #[wasm_bindgen(getter)]
    pub fn context_json(&self) -> String {
        serde_json::to_string(&self.context).unwrap_or_default()
    }

    // === Actions ===

    /// Set to checked state
    pub fn set_checked(&mut self) -> bool {
        if self.context.disabled {
            return false;
        }
        self.context.checked = true;
        self.context.indeterminate = false;
        self.state = "checked".to_string();
        true
    }

    /// Set to unchecked state
    pub fn set_unchecked(&mut self) -> bool {
        if self.context.disabled {
            return false;
        }
        self.context.checked = false;
        self.context.indeterminate = false;
        self.state = "unchecked".to_string();
        true
    }

    /// Set to indeterminate visual state
    pub fn set_indeterminate(&mut self) -> bool {
        if self.context.disabled {
            return false;
        }
        self.context.indeterminate = true;
        self.state = "indeterminate".to_string();
        true
    }
}

impl Default for Checkbox {
    fn default() -> Self {
        Self::new()
    }
}

// === Test Module ===
// Tests are in a separate file for clean separation
#[cfg(test)]
#[path = "tests.rs"]
mod tests;

fn main() {}
