//! Switch Component Scaffold
//!
//! AUTO-GENERATED by rubigo-build - LLM fills in implementation
//!
//! This is a scaffold with method stubs. Run tests and iterate until passing.

use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;

/// Switch context - the extended state (internal, not exposed to JS)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SwitchContext {
    pub checked: bool,
    pub disabled: bool,
    pub read_only: bool,
    pub focused: bool,
}

impl SwitchContext {
    pub fn new() -> Self {
        Self {
            checked: false,
            disabled: false,
            read_only: false,
            focused: false,
        }
    }
}

/// Switch component
#[wasm_bindgen]
pub struct Switch {
    context: SwitchContext,
    state: String,
}

#[wasm_bindgen]
impl Switch {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self {
            context: SwitchContext::new(),
            state: "idle".to_string(),
        }
    }

    // === Getters ===

    #[wasm_bindgen(getter)]
    pub fn state_name(&self) -> String {
        self.state.clone()
    }

    /// Get context as JSON string (for JS interop)
    #[wasm_bindgen(getter)]
    pub fn context_json(&self) -> String {
        serde_json::to_string(&self.context).unwrap_or_default()
    }

    // === Actions ===

    /// Invert the checked state
    pub fn toggle(&mut self) -> bool {
        if self.context.disabled || self.context.read_only {
            return false;
        }
        self.context.checked = !self.context.checked;
        self.state = if self.context.checked {
            "checked"
        } else {
            "unchecked"
        }
        .to_string();
        true
    }

    pub fn set_focused(&mut self) -> bool {
        self.context.focused = true;
        true
    }

    pub fn clear_focused(&mut self) -> bool {
        self.context.focused = false;
        true
    }
}

impl Default for Switch {
    fn default() -> Self {
        Self::new()
    }
}

// === Test Module ===
// Tests are in a separate file for clean separation
#[cfg(test)]
#[path = "tests.rs"]
mod tests;

fn main() {}
