/**
 * Button Keyboard Interaction Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that keyboard handlers are present and work correctly.
 */

import { test, expect, describe } from 'bun:test';
import { useButton } from '../button/solid/useButton';

/**
 * Keyboard Handler Tests
 * 
 * Verify rootProps() includes keyboard event handlers.
 */
describe('Button Keyboard Interactions', () => {
    test('rootProps() includes onKeyDown handler', () => {
        const hook = useButton({});
        const props = hook.rootProps();
        expect(typeof props.onKeyDown).toBe('function');
    });

    test('Enter key is documented: Activate immediately (no pressed state)', () => {
        // This test documents expected behavior for Enter
        // Actual keyboard handling is tested via component integration tests
        const hook = useButton({});
        expect(hook.rootProps).toBeDefined();
    });

    test('Space key is documented: Activate on key up (with pressed visual on key down)', () => {
        // This test documents expected behavior for Space
        // Actual keyboard handling is tested via component integration tests
        const hook = useButton({});
        expect(hook.rootProps).toBeDefined();
    });

    test('Tab key is documented: Focus/unfocus the button', () => {
        // This test documents expected behavior for Tab
        // Actual keyboard handling is tested via component integration tests
        const hook = useButton({});
        expect(hook.rootProps).toBeDefined();
    });

});
