/**
 * Checkbox Emit Callback Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that actions emit callbacks with correct payload when context changes.
 * Pattern: When action mutates context.X, callback onXChange should fire with new value.
 */

import { test, expect, describe } from 'bun:test';
import { useCheckbox } from '../checkbox/solid/useCheckbox';

/**
 * Emit Callback Tests
 */
describe('Checkbox Emit Callbacks', () => {
    test('onChange is called when checked changes via setChecked', () => {
        let callbackFired = false;
        let callbackValue: unknown;
        
        const hook = useCheckbox({
            onChange: (value: unknown) => {
                callbackFired = true;
                callbackValue = value;
            },
        });
        
        // Invoke the action that mutates context.checked
        if (typeof hook.setChecked === 'function') {
            hook.setChecked();
        } else if (typeof hook.triggerProps === 'function') {
            // Fallback: try triggerProps().onClick if direct method not found
            const props = hook.triggerProps();
            if (props && typeof props.onClick === 'function') {
                props.onClick();
            }
        }
        
        // The callback SHOULD have fired with the new context value
        expect(callbackFired).toBe(true);
    });

});
