/**
 * Collapsible Emit Callback Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that actions emit callbacks with correct payload when context changes.
 * Pattern: When action mutates context.X, callback onXChange should fire with new value.
 */

import { test, expect, describe } from 'bun:test';
import { useCollapsible } from '../collapsible/solid/useCollapsible';

/**
 * Emit Callback Tests
 */
describe('Collapsible Emit Callbacks', () => {
    test('onOpenChange is called when open changes via expand', () => {
        let callbackFired = false;
        let callbackValue: unknown;
        
        const hook = useCollapsible({
            onOpenChange: (value: unknown) => {
                callbackFired = true;
                callbackValue = value;
            },
        });
        
        // Invoke the action that mutates context.open
        if (typeof hook.expand === 'function') {
            hook.expand();
        } else if (typeof hook.triggerProps === 'function') {
            // Fallback: try triggerProps().onClick if direct method not found
            const props = hook.triggerProps();
            if (props && typeof props.onClick === 'function') {
                props.onClick();
            }
        }
        
        // The callback SHOULD have fired with the new context value
        expect(callbackFired).toBe(true);
    });

    test('expand is idempotent - calling twice fires onOpenChange once', () => {
        let callCount = 0;
        
        const hook = useCollapsible({
            onOpenChange: () => {
                callCount++;
            },
        });
        
        // Call the action twice
        if (typeof hook.expand === 'function') {
            hook.expand();  // First call - should fire callback
            hook.expand();  // Second call - state unchanged, should NOT fire
        }
        
        // Callback should only fire once (on state change), not on redundant calls
        expect(callCount).toBe(1);
    });

});
