/**
 * Dialog Emit Callback Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that actions emit callbacks with correct payload when context changes.
 * Pattern: When action mutates context.X, callback onXChange should fire with new value.
 */

import { test, expect, describe } from 'bun:test';
import { useDialog } from '../dialog/solid/useDialog';

/**
 * Emit Callback Tests
 */
describe('Dialog Emit Callbacks', () => {
    test('onOpenChange is called when open changes via setOpen', () => {
        let callbackFired = false;
        let callbackValue: unknown;
        
        const hook = useDialog({
            onOpenChange: (value: unknown) => {
                callbackFired = true;
                callbackValue = value;
            },
        });
        
        // Invoke the action that mutates context.open
        if (typeof hook.setOpen === 'function') {
            hook.setOpen();
        } else if (typeof hook.triggerProps === 'function') {
            // Fallback: try triggerProps().onClick if direct method not found
            const props = hook.triggerProps();
            if (props && typeof props.onClick === 'function') {
                props.onClick();
            }
        }
        
        // The callback SHOULD have fired with the new context value
        expect(callbackFired).toBe(true);
    });

});
