/**
 * Dialog Keyboard Interaction Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that keyboard handlers are present and work correctly.
 */

import { test, expect, describe } from 'bun:test';
import { useDialog } from '../dialog/solid/useDialog';

/**
 * Keyboard Handler Tests
 * 
 * Verify rootProps() includes keyboard event handlers.
 */
describe('Dialog Keyboard Interactions', () => {
    test('rootProps() includes onKeyDown handler', () => {
        const hook = useDialog({});
        const props = hook.rootProps();
        expect(typeof props.onKeyDown).toBe('function');
    });

    test('Escape key is documented: Close dialog (if not prevented)', () => {
        // This test documents expected behavior for Escape
        // Actual keyboard handling is tested via component integration tests
        const hook = useDialog({});
        expect(hook.rootProps).toBeDefined();
    });

});
