/**
 * Input Emit Callback Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that actions emit callbacks with correct payload when context changes.
 * Pattern: When action mutates context.X, callback onXChange should fire with new value.
 */

import { test, expect, describe } from 'bun:test';
import { useInput } from '../input/solid/useInput';

/**
 * Emit Callback Tests
 */
describe('Input Emit Callbacks', () => {
    test('onChange is called when value changes via setValue', () => {
        let callbackFired = false;
        let callbackValue: unknown;
        
        const hook = useInput({
            onChange: (value: unknown) => {
                callbackFired = true;
                callbackValue = value;
            },
        });
        
        // Invoke the action that mutates context.value
        if (typeof hook.setValue === 'function') {
            hook.setValue();
        } else if (typeof hook.triggerProps === 'function') {
            // Fallback: try triggerProps().onClick if direct method not found
            const props = hook.triggerProps();
            if (props && typeof props.onClick === 'function') {
                props.onClick();
            }
        }
        
        // The callback SHOULD have fired with the new context value
        expect(callbackFired).toBe(true);
    });

});
