/**
 * Input Hook Test: useInput conformance and prop cycling
 * AUTO-GENERATED by rubigo-build – do not edit
 */

import { test, expect, describe } from 'bun:test';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { createSignal, createRoot } from 'solid-js';
import { useInput } from '../input/solid/useInput';

interface UnifiedVectors {
    component: string;
    scenarios: Array<{
        name: string;
        source: 'yaml' | 'itf';
        steps: Array<{
            event: string;
            before: { context: Record<string, unknown>; state: string };
            after: { context: Record<string, unknown>; state: string };
        }>;
    }>;
}

function loadVectors(): UnifiedVectors | null {
    const vectorsPath = join(process.cwd(), '..', 'generated', 'test-vectors', 'input.unified.json');
    if (!existsSync(vectorsPath)) {
        console.warn(`No unified vectors found at ${vectorsPath}`);
        return null;
    }
    return JSON.parse(readFileSync(vectorsPath, 'utf-8'));
}

describe('Input Hook Conformance', () => {
    const vectors = loadVectors();

    if (!vectors) {
        test.skip('No vectors available - run just unify-vectors first', () => { });
        return;
    }

    test('loads unified vectors', () => {
        expect(vectors.component).toBe('input');
        expect(vectors.scenarios.length).toBeGreaterThan(0);
    });
});

/**
 * Prop Cycling Tests
 * 
 * These tests verify that boolean props can be cycled multiple times
 * on the SAME hook instance without state corruption.
 */
describe('Input Prop Cycling', () => {
    test('disabled cycling: false→true→false→true (same instance)', () => {
        createRoot((dispose) => {
            const [props, setProps] = createSignal({ disabled: false });
            const hook = useInput(() => props());
            
            expect(hook.disabled()).toBe(false);
            setProps({ disabled: true });
            expect(hook.disabled()).toBe(true);
            setProps({ disabled: false });
            expect(hook.disabled()).toBe(false);
            setProps({ disabled: true });
            expect(hook.disabled()).toBe(true);
            
            dispose();
        });
    });

});

/**
 * Event Dispatch Tests
 */
describe('Input Event Dispatch', () => {
});

/**
 * Accessor Reactivity Tests
 */
describe('Input Accessor Reactivity', () => {
    test('disabled() accessor returns boolean', () => {
        const hook = useInput({});
        expect(typeof hook.disabled()).toBe('boolean');
    });

});
