/**
 * Input Component ARIA Conformance Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that rootProps() returns correct ARIA attributes per state.
 */

import { test, expect, describe } from 'bun:test';
import { useInput } from '../input/solid/useInput';

/**
 * ARIA Conformance Tests
 */
describe('Input ARIA Conformance', () => {
    test('rootProps() returns object with ARIA attributes', () => {
        const hook = useInput({});
        const props = hook.rootProps();
        expect(typeof props).toBe('object');
    });

    test('rootProps() includes aria-disabled', () => {
        const hook = useInput({});
        const props = hook.rootProps();
        expect('aria-disabled' in props).toBe(true);
    });

    test('rootProps() includes aria-invalid', () => {
        const hook = useInput({});
        const props = hook.rootProps();
        expect('aria-invalid' in props).toBe(true);
    });

    test('rootProps() includes aria-readonly', () => {
        const hook = useInput({});
        const props = hook.rootProps();
        expect('aria-readonly' in props).toBe(true);
    });

});
