/**
 * Select Emit Callback Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that actions emit callbacks with correct payload when context changes.
 * Pattern: When action mutates context.X, callback onXChange should fire with new value.
 */

import { test, expect, describe } from 'bun:test';
import { useSelect } from '../select/solid/useSelect';

/**
 * Emit Callback Tests
 */
describe('Select Emit Callbacks', () => {
    test('onOpenChange is called when open changes via openMenu', () => {
        let callbackFired = false;
        let callbackValue: unknown;
        
        const hook = useSelect({
            onOpenChange: (value: unknown) => {
                callbackFired = true;
                callbackValue = value;
            },
        });
        
        // Invoke the action that mutates context.open
        if (typeof hook.openMenu === 'function') {
            hook.openMenu();
        } else if (typeof hook.triggerProps === 'function') {
            // Fallback: try triggerProps().onClick if direct method not found
            const props = hook.triggerProps();
            if (props && typeof props.onClick === 'function') {
                props.onClick();
            }
        }
        
        // The callback SHOULD have fired with the new context value
        expect(callbackFired).toBe(true);
    });

    test('onValueChange is called when selectedValue changes via selectOption', () => {
        let callbackFired = false;
        let callbackValue: unknown;
        
        const hook = useSelect({
            onValueChange: (value: unknown) => {
                callbackFired = true;
                callbackValue = value;
            },
        });
        
        // Invoke the action that mutates context.selectedValue
        if (typeof hook.selectOption === 'function') {
            hook.selectOption();
        } else if (typeof hook.triggerProps === 'function') {
            // Fallback: try triggerProps().onClick if direct method not found
            const props = hook.triggerProps();
            if (props && typeof props.onClick === 'function') {
                props.onClick();
            }
        }
        
        // The callback SHOULD have fired with the new context value
        expect(callbackFired).toBe(true);
    });

});
