/**
 * Switch Emit Callback Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that actions emit callbacks with correct payload when context changes.
 * Pattern: When action mutates context.X, callback onXChange should fire with new value.
 */

import { test, expect, describe } from 'bun:test';
import { useSwitch } from '../switch/solid/useSwitch';

/**
 * Emit Callback Tests
 */
describe('Switch Emit Callbacks', () => {
    test('onCheckedChange is called when checked changes via toggle', () => {
        let callbackFired = false;
        let callbackValue: unknown;
        
        const hook = useSwitch({
            onCheckedChange: (value: unknown) => {
                callbackFired = true;
                callbackValue = value;
            },
        });
        
        // Invoke the action that mutates context.checked
        if (typeof hook.toggle === 'function') {
            hook.toggle();
        } else if (typeof hook.triggerProps === 'function') {
            // Fallback: try triggerProps().onClick if direct method not found
            const props = hook.triggerProps();
            if (props && typeof props.onClick === 'function') {
                props.onClick();
            }
        }
        
        // The callback SHOULD have fired with the new context value
        expect(callbackFired).toBe(true);
    });

});
