/**
 * Switch Component ARIA Conformance Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that rootProps() returns correct ARIA attributes per state.
 */

import { test, expect, describe } from 'bun:test';
import { useSwitch } from '../switch/solid/useSwitch';

/**
 * ARIA Conformance Tests
 */
describe('Switch ARIA Conformance', () => {
    test('rootProps() returns object with ARIA attributes', () => {
        const hook = useSwitch({});
        const props = hook.rootProps();
        expect(typeof props).toBe('object');
    });

    test('rootProps() includes aria-checked', () => {
        const hook = useSwitch({});
        const props = hook.rootProps();
        expect('aria-checked' in props).toBe(true);
    });

    test('rootProps() includes aria-disabled', () => {
        const hook = useSwitch({});
        const props = hook.rootProps();
        expect('aria-disabled' in props).toBe(true);
    });

});
