/**
 * Tabs Component ARIA Conformance Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that rootProps() returns correct ARIA attributes per state.
 */

import { test, expect, describe } from 'bun:test';
import { useTabs } from '../tabs/solid/useTabs';

/**
 * ARIA Conformance Tests
 */
describe('Tabs ARIA Conformance', () => {
    test('rootProps() returns object with ARIA attributes', () => {
        const hook = useTabs({});
        const props = hook.rootProps();
        expect(typeof props).toBe('object');
    });

    test('rootProps() includes aria-selected', () => {
        const hook = useTabs({});
        const props = hook.rootProps();
        expect('aria-selected' in props).toBe(true);
    });

});
