/**
 * Tabs Emit Callback Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that actions emit callbacks with correct payload when context changes.
 * Pattern: When action mutates context.X, callback onXChange should fire with new value.
 */

import { test, expect, describe } from 'bun:test';
import { useTabs } from '../tabs/solid/useTabs';

/**
 * Emit Callback Tests
 */
describe('Tabs Emit Callbacks', () => {
    test('onTabChange is called when selectedId changes via setSelected', () => {
        let callbackFired = false;
        let callbackValue: unknown;
        
        const hook = useTabs({
            onTabChange: (value: unknown) => {
                callbackFired = true;
                callbackValue = value;
            },
        });
        
        // Invoke the action that mutates context.selectedId
        if (typeof hook.setSelected === 'function') {
            hook.setSelected();
        } else if (typeof hook.triggerProps === 'function') {
            // Fallback: try triggerProps().onClick if direct method not found
            const props = hook.triggerProps();
            if (props && typeof props.onClick === 'function') {
                props.onClick();
            }
        }
        
        // The callback SHOULD have fired with the new context value
        expect(callbackFired).toBe(true);
    });

});
