/**
 * ToggleGroup Emit Callback Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that actions emit callbacks with correct payload when context changes.
 * Pattern: When action mutates context.X, callback onXChange should fire with new value.
 */

import { test, expect, describe } from 'bun:test';
import { useToggleGroup } from '../togglegroup/solid/useToggleGroup';

/**
 * Emit Callback Tests
 */
describe('ToggleGroup Emit Callbacks', () => {
    test('onValueChange is called when selectedId changes via selectItem', () => {
        let callbackFired = false;
        let callbackValue: unknown;
        
        const hook = useToggleGroup({
            onValueChange: (value: unknown) => {
                callbackFired = true;
                callbackValue = value;
            },
        });
        
        // Invoke the action that mutates context.selectedId
        if (typeof hook.selectItem === 'function') {
            hook.selectItem();
        } else if (typeof hook.triggerProps === 'function') {
            // Fallback: try triggerProps().onClick if direct method not found
            const props = hook.triggerProps();
            if (props && typeof props.onClick === 'function') {
                props.onClick();
            }
        }
        
        // The callback SHOULD have fired with the new context value
        expect(callbackFired).toBe(true);
    });

});
