/**
 * ToggleGroup Component ARIA Conformance Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that rootProps() returns correct ARIA attributes per state.
 */

import { test, expect, describe } from 'bun:test';
import { useToggleGroup } from '../togglegroup/solid/useToggleGroup';

/**
 * ARIA Conformance Tests
 */
describe('ToggleGroup ARIA Conformance', () => {
    test('rootProps() returns object with ARIA attributes', () => {
        const hook = useToggleGroup({});
        const props = hook.rootProps();
        expect(typeof props).toBe('object');
    });

    // Note: aria-checked belongs on items, not on root element

    test('rootProps() includes aria-disabled', () => {
        const hook = useToggleGroup({});
        const props = hook.rootProps();
        expect('aria-disabled' in props).toBe(true);
    });

});
