/**
 * Tooltip Component ARIA Conformance Tests
 * AUTO-GENERATED by rubigo-build – do not edit
 * 
 * Tests that rootProps() returns correct ARIA attributes per state.
 */

import { test, expect, describe } from 'bun:test';
import { useTooltip } from '../tooltip/solid/useTooltip';

/**
 * ARIA Conformance Tests
 */
describe('Tooltip ARIA Conformance', () => {
    test('rootProps() returns object with ARIA attributes', () => {
        const hook = useTooltip({});
        const props = hook.rootProps();
        expect(typeof props).toBe('object');
    });

    test('rootProps() includes aria-hidden', () => {
        const hook = useTooltip({});
        const props = hook.rootProps();
        expect('aria-hidden' in props).toBe(true);
    });

});
