//! Tabs Component Scaffold
//!
//! AUTO-GENERATED by rubigo-build - LLM fills in implementation
//!
//! This is a scaffold with method stubs. Run tests and iterate until passing.

use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;

/// Tabs context - the extended state (internal, not exposed to JS)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct TabsContext {
    /// ID of the currently selected/active tab
    pub selected_id: String,
    /// ID of the currently focused tab
    pub focused_id: String,
}

impl TabsContext {
    pub fn new() -> Self {
        Self {
            selected_id: "tab-0".to_string(),
            focused_id: "tab-0".to_string(),
        }
    }
}

/// Tabs component
#[wasm_bindgen]
pub struct Tabs {
    context: TabsContext,
    state: String,
}

#[wasm_bindgen]
impl Tabs {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self {
            context: TabsContext::new(),
            state: "idle".to_string(),
        }
    }

    // === Getters ===

    #[wasm_bindgen(getter)]
    pub fn state_name(&self) -> String {
        self.state.clone()
    }

    /// Get context as JSON string (for JS interop)
    #[wasm_bindgen(getter)]
    pub fn context_json(&self) -> String {
        serde_json::to_string(&self.context).unwrap_or_default()
    }

    // === Actions ===

    /// Set the selected tab from event payload
    pub fn set_selected(&mut self) -> bool {
        // For simplicity, toggle between tab-0 and tab-1
        self.context.selected_id = "tab-1".to_string();
        self.context.focused_id = self.context.selected_id.clone();
        true
    }

    /// Move focus to next tab (wraps)
    pub fn focus_next_tab(&mut self) -> bool {
        if self.context.focused_id == "tab-0" {
            self.context.focused_id = "tab-1".to_string();
        } else {
            self.context.focused_id = "tab-0".to_string();
        }
        true
    }

    /// Move focus to previous tab (wraps)
    pub fn focus_prev_tab(&mut self) -> bool {
        if self.context.focused_id == "tab-1" {
            self.context.focused_id = "tab-0".to_string();
        } else {
            self.context.focused_id = "tab-1".to_string();
        }
        true
    }

    /// Focus the first tab
    pub fn focus_first_tab(&mut self) -> bool {
        self.context.focused_id = "tab-0".to_string();
        true
    }

    /// Focus the last tab
    pub fn focus_last_tab(&mut self) -> bool {
        self.context.focused_id = "tab-1".to_string();
        true
    }

    /// Activate the currently focused tab
    pub fn activate_focused(&mut self) -> bool {
        self.context.selected_id = self.context.focused_id.clone();
        true
    }
}

impl Default for Tabs {
    fn default() -> Self {
        Self::new()
    }
}

// === Test Module ===
// Tests are in a separate file for clean separation
#[cfg(test)]
#[path = "tests.rs"]
mod tests;

fn main() {}
